// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Price Provides price amount (before tax) - Money structure is used
//
// swagger:model Price
type Price struct {

	// Indicates the (class) type of the price
	AtType string `json:"@type,omitempty"`

	// pre tax amount
	PreTaxAmount *Money `json:"preTaxAmount,omitempty"`

	// price range
	PriceRange *PriceRange `json:"priceRange,omitempty"`
}

// Validate validates this price
func (m *Price) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePreTaxAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceRange(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Price) validatePreTaxAmount(formats strfmt.Registry) error {

	if swag.IsZero(m.PreTaxAmount) { // not required
		return nil
	}

	if m.PreTaxAmount != nil {
		if err := m.PreTaxAmount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preTaxAmount")
			}
			return err
		}
	}

	return nil
}

func (m *Price) validatePriceRange(formats strfmt.Registry) error {

	if swag.IsZero(m.PriceRange) { // not required
		return nil
	}

	if m.PriceRange != nil {
		if err := m.PriceRange.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("priceRange")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Price) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Price) UnmarshalBinary(b []byte) error {
	var res Price
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
