// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProductOfferingQualificationRef Reference to productOfferingQualification previously done to check requested product serviceability
//
// swagger:model ProductOfferingQualificationRef
type ProductOfferingQualificationRef struct {

	// Technical attribute to extend this class
	AtReferredType string `json:"@referredType,omitempty"`

	// Link to the productOfferingQualification
	Href string `json:"href,omitempty"`

	// Id of the productOfferingQualification
	// Required: true
	ID *string `json:"id"`

	// Id of the item of the productOfferingQualification
	// Required: true
	QualificationItem *string `json:"qualificationItem"`
}

// Validate validates this product offering qualification ref
func (m *ProductOfferingQualificationRef) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQualificationItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductOfferingQualificationRef) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ProductOfferingQualificationRef) validateQualificationItem(formats strfmt.Registry) error {

	if err := validate.Required("qualificationItem", "body", m.QualificationItem); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductOfferingQualificationRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductOfferingQualificationRef) UnmarshalBinary(b []byte) error {
	var res ProductOfferingQualificationRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
