/*
 * QLC DOD Service
 *
 * REST Api for QLC DOD Service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Model400ErrorResponseError struct {
	Message   string       `json:"message,omitempty"`
	LngString *interface{} `json:"lngString,omitempty"`
}
