/*
 * QLC DOD Service
 *
 * REST Api for QLC DOD Service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QuoteQuoteItemPriceModel struct {
	PriceType             string                         `json:"priceType,omitempty"`
	RecurringChargePeriod string                         `json:"recurringChargePeriod,omitempty"`
	Name                  string                         `json:"name,omitempty"`
	Price                 *QuoteQuoteItemPriceModelPrice `json:"price,omitempty"`
}
