/*
 * QLC DOD Service
 *
 * REST Api for QLC DOD Service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DltInvoiceGenerateInvoiceByOrderIdResBuyer struct {
	Address string `json:"address,omitempty"`
	Name    string `json:"name,omitempty"`
}
