/*
 * QLC DOD Service
 *
 * REST Api for QLC DOD Service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QualificationProductOfferingQualificationItemModelProductProductSpecificationDescribingEnniIngressBwProfileCir struct {
	Amount float64 `json:"amount,omitempty"`
	Unit   string  `json:"unit,omitempty"`
}
