// Code generated by go-swagger; DO NOT EDIT.

package cancel_product_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCancelProductOrderFindParams creates a new CancelProductOrderFindParams object
// with the default values initialized.
func NewCancelProductOrderFindParams() *CancelProductOrderFindParams {
	var ()
	return &CancelProductOrderFindParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelProductOrderFindParamsWithTimeout creates a new CancelProductOrderFindParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelProductOrderFindParamsWithTimeout(timeout time.Duration) *CancelProductOrderFindParams {
	var ()
	return &CancelProductOrderFindParams{

		timeout: timeout,
	}
}

// NewCancelProductOrderFindParamsWithContext creates a new CancelProductOrderFindParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelProductOrderFindParamsWithContext(ctx context.Context) *CancelProductOrderFindParams {
	var ()
	return &CancelProductOrderFindParams{

		Context: ctx,
	}
}

// NewCancelProductOrderFindParamsWithHTTPClient creates a new CancelProductOrderFindParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelProductOrderFindParamsWithHTTPClient(client *http.Client) *CancelProductOrderFindParams {
	var ()
	return &CancelProductOrderFindParams{
		HTTPClient: client,
	}
}

/*CancelProductOrderFindParams contains all the parameters to send to the API endpoint
for the cancel product order find operation typically these are written to a http.Request
*/
type CancelProductOrderFindParams struct {

	/*ProductOrderExternalID*/
	ProductOrderExternalID *string
	/*ProductOrderID*/
	ProductOrderID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel product order find params
func (o *CancelProductOrderFindParams) WithTimeout(timeout time.Duration) *CancelProductOrderFindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel product order find params
func (o *CancelProductOrderFindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel product order find params
func (o *CancelProductOrderFindParams) WithContext(ctx context.Context) *CancelProductOrderFindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel product order find params
func (o *CancelProductOrderFindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel product order find params
func (o *CancelProductOrderFindParams) WithHTTPClient(client *http.Client) *CancelProductOrderFindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel product order find params
func (o *CancelProductOrderFindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductOrderExternalID adds the productOrderExternalID to the cancel product order find params
func (o *CancelProductOrderFindParams) WithProductOrderExternalID(productOrderExternalID *string) *CancelProductOrderFindParams {
	o.SetProductOrderExternalID(productOrderExternalID)
	return o
}

// SetProductOrderExternalID adds the productOrderExternalId to the cancel product order find params
func (o *CancelProductOrderFindParams) SetProductOrderExternalID(productOrderExternalID *string) {
	o.ProductOrderExternalID = productOrderExternalID
}

// WithProductOrderID adds the productOrderID to the cancel product order find params
func (o *CancelProductOrderFindParams) WithProductOrderID(productOrderID *string) *CancelProductOrderFindParams {
	o.SetProductOrderID(productOrderID)
	return o
}

// SetProductOrderID adds the productOrderId to the cancel product order find params
func (o *CancelProductOrderFindParams) SetProductOrderID(productOrderID *string) {
	o.ProductOrderID = productOrderID
}

// WriteToRequest writes these params to a swagger request
func (o *CancelProductOrderFindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProductOrderExternalID != nil {

		// query param productOrderExternalId
		var qrProductOrderExternalID string
		if o.ProductOrderExternalID != nil {
			qrProductOrderExternalID = *o.ProductOrderExternalID
		}
		qProductOrderExternalID := qrProductOrderExternalID
		if qProductOrderExternalID != "" {
			if err := r.SetQueryParam("productOrderExternalId", qProductOrderExternalID); err != nil {
				return err
			}
		}

	}

	if o.ProductOrderID != nil {

		// query param productOrderId
		var qrProductOrderID string
		if o.ProductOrderID != nil {
			qrProductOrderID = *o.ProductOrderID
		}
		qProductOrderID := qrProductOrderID
		if qProductOrderID != "" {
			if err := r.SetQueryParam("productOrderId", qProductOrderID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
