// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProductGetParams creates a new ProductGetParams object
// with the default values initialized.
func NewProductGetParams() *ProductGetParams {
	var ()
	return &ProductGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProductGetParamsWithTimeout creates a new ProductGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProductGetParamsWithTimeout(timeout time.Duration) *ProductGetParams {
	var ()
	return &ProductGetParams{

		timeout: timeout,
	}
}

// NewProductGetParamsWithContext creates a new ProductGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewProductGetParamsWithContext(ctx context.Context) *ProductGetParams {
	var ()
	return &ProductGetParams{

		Context: ctx,
	}
}

// NewProductGetParamsWithHTTPClient creates a new ProductGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProductGetParamsWithHTTPClient(client *http.Client) *ProductGetParams {
	var ()
	return &ProductGetParams{
		HTTPClient: client,
	}
}

/*ProductGetParams contains all the parameters to send to the API endpoint
for the product get operation typically these are written to a http.Request
*/
type ProductGetParams struct {

	/*ProductID*/
	ProductID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the product get params
func (o *ProductGetParams) WithTimeout(timeout time.Duration) *ProductGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the product get params
func (o *ProductGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the product get params
func (o *ProductGetParams) WithContext(ctx context.Context) *ProductGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the product get params
func (o *ProductGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the product get params
func (o *ProductGetParams) WithHTTPClient(client *http.Client) *ProductGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the product get params
func (o *ProductGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductID adds the productID to the product get params
func (o *ProductGetParams) WithProductID(productID string) *ProductGetParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the product get params
func (o *ProductGetParams) SetProductID(productID string) {
	o.ProductID = productID
}

// WriteToRequest writes these params to a swagger request
func (o *ProductGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ProductId
	if err := r.SetPathParam("ProductId", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
