// Code generated by go-swagger; DO NOT EDIT.

package orchestra_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-lsobus/cmd/agent/models"
)

// ExecGetReader is a Reader for the ExecGet structure.
type ExecGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExecGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExecGetOK creates a ExecGetOK with default headers values
func NewExecGetOK() *ExecGetOK {
	return &ExecGetOK{}
}

/*ExecGetOK handles this case with default header values.

A successful response.
*/
type ExecGetOK struct {
	Payload *models.ProtoOrchestraCommonResponse
}

func (o *ExecGetOK) Error() string {
	return fmt.Sprintf("[POST /orchestra/exec/get][%d] execGetOK  %+v", 200, o.Payload)
}

func (o *ExecGetOK) GetPayload() *models.ProtoOrchestraCommonResponse {
	return o.Payload
}

func (o *ExecGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoOrchestraCommonResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
