// Code generated by go-swagger; DO NOT EDIT.

package orchestra_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-lsobus/cmd/agent/models"
)

// ExecFindReader is a Reader for the ExecFind structure.
type ExecFindReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecFindReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExecFindOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExecFindOK creates a ExecFindOK with default headers values
func NewExecFindOK() *ExecFindOK {
	return &ExecFindOK{}
}

/*ExecFindOK handles this case with default header values.

A successful response.
*/
type ExecFindOK struct {
	Payload *models.ProtoOrchestraCommonResponse
}

func (o *ExecFindOK) Error() string {
	return fmt.Sprintf("[POST /orchestra/exec/find][%d] execFindOK  %+v", 200, o.Payload)
}

func (o *ExecFindOK) GetPayload() *models.ProtoOrchestraCommonResponse {
	return o.Payload
}

func (o *ExecFindOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoOrchestraCommonResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
