// Code generated by go-swagger; DO NOT EDIT.

package orchestra_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-lsobus/cmd/agent/models"
)

// NewExecGetParams creates a new ExecGetParams object
// with the default values initialized.
func NewExecGetParams() *ExecGetParams {
	var ()
	return &ExecGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExecGetParamsWithTimeout creates a new ExecGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExecGetParamsWithTimeout(timeout time.Duration) *ExecGetParams {
	var ()
	return &ExecGetParams{

		timeout: timeout,
	}
}

// NewExecGetParamsWithContext creates a new ExecGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewExecGetParamsWithContext(ctx context.Context) *ExecGetParams {
	var ()
	return &ExecGetParams{

		Context: ctx,
	}
}

// NewExecGetParamsWithHTTPClient creates a new ExecGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExecGetParamsWithHTTPClient(client *http.Client) *ExecGetParams {
	var ()
	return &ExecGetParams{
		HTTPClient: client,
	}
}

/*ExecGetParams contains all the parameters to send to the API endpoint
for the exec get operation typically these are written to a http.Request
*/
type ExecGetParams struct {

	/*Body*/
	Body *models.ProtoOrchestraCommonRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the exec get params
func (o *ExecGetParams) WithTimeout(timeout time.Duration) *ExecGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the exec get params
func (o *ExecGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the exec get params
func (o *ExecGetParams) WithContext(ctx context.Context) *ExecGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the exec get params
func (o *ExecGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the exec get params
func (o *ExecGetParams) WithHTTPClient(client *http.Client) *ExecGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the exec get params
func (o *ExecGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the exec get params
func (o *ExecGetParams) WithBody(body *models.ProtoOrchestraCommonRequest) *ExecGetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the exec get params
func (o *ExecGetParams) SetBody(body *models.ProtoOrchestraCommonRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ExecGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
