// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductSpecification A ProductSpec describes the invariant properties (i.e., features) that a given set of Products MAY have. These properties provide the information needed to plan, construct, allocate, and/or retire the Services and Resources from the operator environment needed to deliver the Product
//
// swagger:model ProductSpecification
type ProductSpecification struct {

	// describing
	Describing *Describing `json:"describing,omitempty"`

	// A unique identifier for the product spec, within the product spec domain. It is assigned by the seller and communicated to the buyer at on-boarding time.
	ID string `json:"id,omitempty"`
}

// Validate validates this product specification
func (m *ProductSpecification) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescribing(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductSpecification) validateDescribing(formats strfmt.Registry) error {

	if swag.IsZero(m.Describing) { // not required
		return nil
	}

	if m.Describing != nil {
		if err := m.Describing.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("describing")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductSpecification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductSpecification) UnmarshalBinary(b []byte) error {
	var res ProductSpecification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
