// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerminationError Termination error may be provided if seller is unable to perform qualification
//
// swagger:model TerminationError
type TerminationError struct {

	// Id of the termination error
	ID string `json:"id,omitempty"`

	// Value (text) for the termination error
	Value string `json:"value,omitempty"`
}

// Validate validates this termination error
func (m *TerminationError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TerminationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerminationError) UnmarshalBinary(b []byte) error {
	var res TerminationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
