// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProductOrderRef A reference to a productOrder and optionally to an order item.
//
// swagger:model ProductOrderRef
type ProductOrderRef struct {

	// Hyperlink to the productOrder
	Href string `json:"href,omitempty"`

	// Identifier of the productOrder(provided by the seller)
	// Required: true
	ID *string `json:"id"`

	// Identifier of the line item (generally it is a sequence number 01, 02, 03, ...)
	// Required: true
	OrderItemID *string `json:"orderItemId"`
}

// Validate validates this product order ref
func (m *ProductOrderRef) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderItemID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductOrderRef) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ProductOrderRef) validateOrderItemID(formats strfmt.Registry) error {

	if err := validate.Required("orderItemId", "body", m.OrderItemID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductOrderRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductOrderRef) UnmarshalBinary(b []byte) error {
	var res ProductOrderRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
