// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoConnectionStaticParam proto connection static param
//
// swagger:model protoConnectionStaticParam
type ProtoConnectionStaticParam struct {

	// product offering Id
	ProductOfferingID string `json:"ProductOfferingId,omitempty"`

	// buyer product Id
	BuyerProductID string `json:"buyerProductId,omitempty"`

	// dst city
	DstCity string `json:"dstCity,omitempty"`

	// dst company name
	DstCompanyName string `json:"dstCompanyName,omitempty"`

	// dst data center
	DstDataCenter string `json:"dstDataCenter,omitempty"`

	// dst port
	DstPort string `json:"dstPort,omitempty"`

	// dst region
	DstRegion string `json:"dstRegion,omitempty"`

	// product Id
	ProductID string `json:"productId,omitempty"`

	// src city
	SrcCity string `json:"srcCity,omitempty"`

	// src company name
	SrcCompanyName string `json:"srcCompanyName,omitempty"`

	// src data center
	SrcDataCenter string `json:"srcDataCenter,omitempty"`

	// src port
	SrcPort string `json:"srcPort,omitempty"`

	// src region
	SrcRegion string `json:"srcRegion,omitempty"`
}

// Validate validates this proto connection static param
func (m *ProtoConnectionStaticParam) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoConnectionStaticParam) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoConnectionStaticParam) UnmarshalBinary(b []byte) error {
	var res ProtoConnectionStaticParam
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
