// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoVersionResponse proto version response
//
// swagger:model protoVersionResponse
type ProtoVersionResponse struct {

	// build time
	BuildTime string `json:"buildTime,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this proto version response
func (m *ProtoVersionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoVersionResponse) UnmarshalBinary(b []byte) error {
	var res ProtoVersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
