// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoTerminateOrderParam proto terminate order param
//
// swagger:model protoTerminateOrderParam
type ProtoTerminateOrderParam struct {

	// buyer
	Buyer *ProtoUser `json:"buyer,omitempty"`

	// privacy
	Privacy *ProtoContractPrivacyParam `json:"privacy,omitempty"`

	// seller
	Seller *ProtoUser `json:"seller,omitempty"`

	// terminate connection param
	TerminateConnectionParam []*ProtoTerminateConnectionParam `json:"terminateConnectionParam"`
}

// Validate validates this proto terminate order param
func (m *ProtoTerminateOrderParam) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuyer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivacy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeller(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTerminateConnectionParam(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoTerminateOrderParam) validateBuyer(formats strfmt.Registry) error {

	if swag.IsZero(m.Buyer) { // not required
		return nil
	}

	if m.Buyer != nil {
		if err := m.Buyer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buyer")
			}
			return err
		}
	}

	return nil
}

func (m *ProtoTerminateOrderParam) validatePrivacy(formats strfmt.Registry) error {

	if swag.IsZero(m.Privacy) { // not required
		return nil
	}

	if m.Privacy != nil {
		if err := m.Privacy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("privacy")
			}
			return err
		}
	}

	return nil
}

func (m *ProtoTerminateOrderParam) validateSeller(formats strfmt.Registry) error {

	if swag.IsZero(m.Seller) { // not required
		return nil
	}

	if m.Seller != nil {
		if err := m.Seller.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("seller")
			}
			return err
		}
	}

	return nil
}

func (m *ProtoTerminateOrderParam) validateTerminateConnectionParam(formats strfmt.Registry) error {

	if swag.IsZero(m.TerminateConnectionParam) { // not required
		return nil
	}

	for i := 0; i < len(m.TerminateConnectionParam); i++ {
		if swag.IsZero(m.TerminateConnectionParam[i]) { // not required
			continue
		}

		if m.TerminateConnectionParam[i] != nil {
			if err := m.TerminateConnectionParam[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("terminateConnectionParam" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProtoTerminateOrderParam) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoTerminateOrderParam) UnmarshalBinary(b []byte) error {
	var res ProtoTerminateOrderParam
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
