// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoUser proto user
//
// swagger:model protoUser
type ProtoUser struct {

	// address
	Address string `json:"address,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this proto user
func (m *ProtoUser) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoUser) UnmarshalBinary(b []byte) error {
	var res ProtoUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
