// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-lsobus/sonata/notify/poq/models"
)

// NewNotificationProductOfferingQualificationStateChangeNotificationParams creates a new NotificationProductOfferingQualificationStateChangeNotificationParams object
// no default values defined in spec.
func NewNotificationProductOfferingQualificationStateChangeNotificationParams() NotificationProductOfferingQualificationStateChangeNotificationParams {

	return NotificationProductOfferingQualificationStateChangeNotificationParams{}
}

// NotificationProductOfferingQualificationStateChangeNotificationParams contains all the bound params for the notification product offering qualification state change notification operation
// typically these are obtained from a http.Request
//
// swagger:parameters notificationProductOfferingQualificationStateChangeNotification
type NotificationProductOfferingQualificationStateChangeNotificationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	ProductOfferingQualificationStateChangeNotification *models.Event
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewNotificationProductOfferingQualificationStateChangeNotificationParams() beforehand.
func (o *NotificationProductOfferingQualificationStateChangeNotificationParams) BindRequest(
	r *http.Request, route *middleware.MatchedRoute,
) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Event
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("productOfferingQualificationStateChangeNotification", "body", nil))
			} else {
				res = append(res, errors.NewParseError("productOfferingQualificationStateChangeNotification", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ProductOfferingQualificationStateChangeNotification = &body
			}
		}
	} else {
		res = append(res, errors.Required("productOfferingQualificationStateChangeNotification", "body", nil))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
