// Code generated by go-swagger; DO NOT EDIT.

package geographic_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new geographic address API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for geographic address API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GeographicAddressGet(params *GeographicAddressGetParams) (*GeographicAddressGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GeographicAddressGet retrieves address

  The Buyer requests the full details of a single Address based on an Address identifier that was previously provided by the Seller.
*/
func (a *Client) GeographicAddressGet(params *GeographicAddressGetParams) (*GeographicAddressGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGeographicAddressGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "geographicAddressGet",
		Method:             "GET",
		PathPattern:        "/geographicAddress/{GeographicAddressId}",
		ProducesMediaTypes: []string{"application/json;charset=utf-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GeographicAddressGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GeographicAddressGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for geographicAddressGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
